- hosts: nagios-server
  sudo: yes
  roles:
    - { role: selinux, selinux_state: permissive, selinux_policy: targeted }
    - { role: nagios}
  vars_files:
    - group_vars/all
    - vars/nagios.yml
  tags:
    - nagios-server

- hosts: all
  sudo: yes
  roles:
    - { role: nagios-agent }
  vars_files:
    - group_vars/all
    - vars/nrpe.yml
  tags:
    - nrpe


