- hosts: go-agent
  sudo: yes
  roles:
    - { role: bahmni-pre-deploy }
  tags: setup

- hosts: go-agent
  tasks:
    - name: Run bahmni installer
      shell: "bahmni -i inventory install"
  tags: install
