# Run from go-agent
- name: Deleting temporal files
  file:
    path=/etc/bahmni-installer
    state=absent
  ignore_errors: true

- name: Remove bahmni-installer
  yum: name=bahmni-installer state=absent

- name: Find the path of bahmni-installer
  find:
    paths: "{{ installer_location }}"
    patterns: bahmni-installer-*.noarch.rpm
  register: bahmni_installer_path
  failed_when: bahmni_installer_path.matched != 1

- name: Install yum
  yum: name={{ bahmni_installer_path.files[0].path }} state=present

- name: Copy bahmni-tw-playbooks to inventory file
  command: cp {{ base_path }}/bahmni-tw-playbooks/{{ environment_name }} /etc/bahmni-installer/inventory

- name: Copy setup.xml
  template: src=setup.yml.j2 dest=/etc/bahmni-installer/setup.yml

- name: Run install nagios
  command: "bahmni -i inventory install-nagios"
