# Run from agent
- name: Deleting temporal files
  file:
    path=/etc/bahmni-installer
    state=absent
  ignore_errors: true

- name: Remove bahmni-installer
  yum: name=bahmni-installer state=absent

- name: Find the path of bahmni-installer
  find:
    paths: "{{ installer_location }}"
    patterns: bahmni-installer-*.noarch.rpm
  register: bahmni_installer_path
  failed_when: bahmni_installer_path.matched != 1

- name: Install bahmni-installer rpm
  yum: name={{ bahmni_installer_path.files[0].path }} state=present

- name: Download {{ implementation_name }} config zip from git
  get_url:
    url={{ config_url }}
    force=yes
    dest=/etc/bahmni-installer/deployment-artifacts/{{ implementation_name }}_{{ branch }}.zip
    mode=0644
  when: implementation_name != 'default'

- name: Unzip downloaded config file
  unarchive:
    src=/etc/bahmni-installer/deployment-artifacts/{{ implementation_name }}_{{ branch }}.zip
    dest=/etc/bahmni-installer/deployment-artifacts
    creates=yes
    mode=0755
  when: implementation_name != 'default'

- name: Renaming config file
  command: mv -f /etc/bahmni-installer/deployment-artifacts/{{ implementation_name }}-config-{{ branch }} /etc/bahmni-installer/deployment-artifacts/{{ implementation_name }}_config
  when: implementation_name != 'default'

- name: Copy bahmni-tw-playbooks to inventory file
  command: cp {{ base_path }}/bahmni-tw-playbooks/{{ environment_name }} /etc/bahmni-installer/inventory

- name: Copy setup.xml
  template: src=setup.yml.j2 dest=/etc/bahmni-installer/setup.yml
