- name: Download letsencrypt
  unarchive: src=https://github.com/letsencrypt/letsencrypt/archive/v{{letsencrypt_version}}.tar.gz dest={{letsencrypt_dest_on_droplet}} copy=no

- name: Rename the letsencrypt folder
  file: src=certbot-{{ letsencrypt_version }} dest=letsencrypt state=link

- name: Generate certs for bahmni domain
  command: letsencrypt/letsencrypt-auto --renew-by-default certonly --agree-tos --email '{{ letsencrypt_notification_email }}' --standalone -d {{ domain_name }}

- name: Copy certs folder to go-agent
  sudo: no
  synchronize: mode=pull src=/etc/letsencrypt/archive/{{ domain_name }} dest={{ certs_destination }}
