- name: Wait for port 22 to become available.
  local_action: "wait_for port=22 host={{ inventory_hostname }}"

- name: Download letsencrypt
  unarchive: src=https://github.com/letsencrypt/letsencrypt/archive/v{{letsencrypt_version}}.tar.gz dest={{letsencrypt_dest_on_droplet}} copy=no

- name: Rename the letsencrypt folder
  file: src=letsencrypt-{{ letsencrypt_version }} dest=letsencrypt state=link

- name: Generate certs for bahmni domain
  command: letsencrypt/letsencrypt-auto --renew certonly --agree-tos --email '{{ letsencrypt_notification_email }}' --standalone --staging -d {{ domain_name }}

- name: Copy certs folder to go-agent
  sudo: no
  synchronize: mode=pull src=/etc/letsencrypt/live/{{ domain_name }} dest= {{certs_destination}}
